### PR TITLE
feature/osep-04-update

### PR DESCRIPTION
**Pull request by pwalsh**
Here are some significant updates to OSEP-04. Everything needs discussion, and I doubt this is the final version. However, it should give us additional material to talk around.

Of note:
- Greatly fleshed out the `mapping` object (was `openspending.mapping`). This has been significantly influenced by @pudo's work [here](https://gist.github.com/pudo/d810d91778e73e991b48), even if it doesn't fully conform to it.
- Tried to give more explanation of the distinction between this and BDP, and why this is different
- Possibly the most controversial and subject to change, I attempted to explicitly flesh out different taxonomies: https://github.com/pwalsh/osep/blob/feature/osep-04-update/osep-04.md#taxonomy
  - I'm not sure if others will see the utility of this
  - I **do** see the utility, as I have piles of municipal data that employs two co-existing taxonomies at the source - functional and economic. I'm curious for feedback on this on two levels: (i) general utility, and (ii) if it is too complex to introduce to OSDP at this stage
- Several examples that progressively show more features of the spec: https://github.com/pwalsh/osep/blob/feature/osep-04-update/osep-04.md#examples

### CODE REVIEW

**Comment by aivuk** [comment]
Minor question: why are you using arrays in the attributes values?

```
   "payee":  {  # a dimension made up of attributes
     "id": ["budget/payee_id"],
     "title": ["budget/payee_name"]
   }
```

Instead of:

```
   "payee":  {  # a dimension made up of attributes
     "id": "budget/payee_id",
     "title": "budget/payee_name"
   }
```

Won't these attributes always be unique?

**Comment by pwalsh** [comment]
Hi @aivuk 

We actually plan to support strings and arrays (see examples above by @rgrp).

The reason for arrays is for cases where multiple files make up the data source for a particular "model" (perhaps because of file size reasons, or other).

**Comment by aivuk** [comment]
@pwalsh 

I saw @rgrp examples and [yours](https://github.com/pwalsh/osep/blob/feature/osep-04-update/osep-04.md#examples), but it is not clear too me what is the meaning of something like this:

```
 "payee":  {  # a dimension made up of attributes
   "id": ["budget/payee_id", "another_resource/payee_id"],
   "title": ["budget/payee_name", "another_resource/payee_id"]
 }
```

You can have multiples files making the data source, but looks to me that these attributes mappings will be always unique. And if it's going to be unique, you don't need to use an array at all.

**Comment by pwalsh** [comment]
@aivuk 

So, in my example, I have a `budget.csv`

```
# budget.csv
pk,budget,budget_date
1,10000,01/01/2015
```

But imagine a scenario where the budget lines are spread across multiple files - either due to file size (we recommend 10MB as the maximum file size), or other administrative reasons. Then we might have this instead:

```
# budget1.csv
pk,budget,budget_date
1,10000,01/01/2015
```

```
# budget2.csv
pk,budget,budget_date
1,10000,01/01/2015
```

```
# budget3.csv
pk,budget,budget_date
1,10000,01/01/2015
```

and there, for the transaction amount mapping, we'd have:

`"amount": ["budget1/budget", "budget2/budget", "budget3/budget"]`

**Comment by pwalsh** [comment]
@rgrp ok, I prepped some examples based on your comments:
- https://github.com/pwalsh/osep/blob/feature/osep-04-update/_includes/minimal.json
- https://github.com/pwalsh/osep/blob/feature/osep-04-update/_includes/entities-denormalized.json
- https://github.com/pwalsh/osep/blob/feature/osep-04-update/_includes/entities-normalized.json
- https://github.com/pwalsh/osep/blob/feature/osep-04-update/_includes/with-classification.json

Notes:
- I left `taxonomy` => `functional` because there haven't yet been any comments on what I did there with taxonomy, and, if we do accept that there are different types of taxonomies, we do need to represent these somehow
- I still feel it would be more consistent to next id + amount + date inside `transaction` (but agree on dropping the further nesting under `attributes`)

**Comment by rufuspollock** [comment]
@pwalsh the reason for not putting under transaction as you are again introducing your "concepts" by a side door. Maybe other stuff should go under transaction (what other attributes would be suitable etc etc). I may be wrong but I'd keep it as simple as possible to start with.

Note: very strong of time atm so suggest you try and get something reasonable and merge as draft and we get feedback and try implementing.

**Comment by pwalsh** [comment]
@rgrp ok, I'm happy to merge this as draft as is (I'll tidy up some errors in the JSON and replace with the new json files I created). I was hoping to get some feedback from anyone on what I did with taxonomies.

**Comment by rufuspollock** [comment]
@pwalsh what did you do with taxonomies that was special? Point me to the section :-)

**Comment by pwalsh** [comment]
https://github.com/pwalsh/osep/blob/feature/osep-04-update/osep-04.md#taxonomy

https://github.com/pwalsh/osep/blob/feature/osep-04-update/_includes/with-classification.json#L25

**Comment by rufuspollock** [comment]
@pwalsh ok i've looked at this. At the moment this is still a top-level item on mapping which are moving away from, right? (I assume we just haven't updated yet).

I would not have this - i would just have top level stuff like "cofog" or whatever. If we need to flag as taxonomy (and a functional one) we could have some kind of logical "type" we can add this on the dimension.

So specifically in your example i would have:

```
    ...
    "payor": {
      "id": "budget/payor",
      "title": "name"  # note: we really want a way of saying this has been dereferenced!
    },
    # just have this a dimension called cofog
    "cofog": {
        "id": "budget/category",
        "title": "name", # note: we really want a way of saying this has been dereferenced!
      }
    }
```

Re "logical type" we could start having something like:

```
_logicalType": "taxonomy/functional"
```

Or something. Though I wonder what the use is at the moment? One answer would be hinting for the user interface when people edit the interface ... - however i think we really want to aim for the minimum and see how we do.

Summary: let's go to the simple option, get the PR, and try migrating stuff and see what happens.

**Comment by pwalsh** [comment]
@rgrp that helps when the idea is specifically a cofog mapping, but not in the case of "this is a functional classification" in a general sense, which may or may not map to cofog.

**Comment by rufuspollock** [comment]
@pwalsh in that case you'd make up an appropriate name for that classification and use it as the dimension name. That's my point: if we move away from using logical names to classify attributes / dimensions then we should do it for everything.

Again, i'd ask ourselves: what do we get having the logical "concepts" written into the mapping and is it worth the cognitive cost right now? (Clearly there are benefits, but my instinct is to use ockham's KISS and leave it out right now).

**Comment by pwalsh** [comment]
Hi all. I've made another update based largely on the points above by Rufus. I'm merging this as the newest version of the OSEP-04 draft.

**Pull request merged**
